### ISSUE TITLE
[Suggestion] Netsuite ECommerce

### ISSUE THREAD

**Issue by fungku** [ElbertF/Wappalyzer#759]
## Name of the application:

Netsuite SuiteCommerce

## Type of application:

Ecommerce

## URL:

 http://www.netsuite.com/portal/products/netsuite/ecommerce/customers.shtml

## A square image of the application's logo: 

![Netsuite Logo](https://zapier.cachefly.net/storage/services/738c1145baf81042337c6bf4c321f6a8.128x128.png)

## Some suggestions on how to detect the application:

There are two version of NetSuite Ecommerce sites that I can figure. 1) Powered by Venda, and 2) Not powered by Venda.

On the sites not powered by venda, there are usually these cookies:

 * **NS_VER**
 * **NLShopperId**
 * **NLVisitorId**

On the venda-powered sites, there seems to be a HTTP header called: 

 * **X-venda-hitid**

## Example websites that use the application(s):

There really are lots, and some pretty well-known names. Here are a few:
 * http://arsenaldirect.arsenal.com/
 * http://www.igloocoolers.com/
 * http://www.magellangps.com/
 * http://store.metmuseum.org/
 * http://www.lauraashley.com/en/uk/page/home
 * http://www.avago.com.au/

**Comment by fungku** [comment]
Added PR #760

**Comment by ElbertF** [comment]
Cheers. :)
