### ISSUE TITLE
[Chrome] Show icon in address bar instead of toolbar.

### ISSUE THREAD

**Issue by hermajan** [ElbertF/Wappalyzer#765]
In address bar the extension could show single icon, when it is clicked it shows tools which website uses. It can be some optional option instead of showing the icon in toolbar (ĺike now). In address bar it will have smaller icon than in toolbar (it saves space on screen). I think there it will be more logical place for extension, because it shows information about the current website.

**Comment by ElbertF** [comment]
You're probably right about it being a more suitable place. `pageAction` doesn't support badges though so we'd lose that functionality.

https://developer.chrome.com/extensions/browserAction
https://developer.chrome.com/extensions/pageAction

**Comment by hermajan** [comment]
If badges is useful for someone it can be second option for showing the extension. Imho extension isn't need to be always visible and then it will use pageAction.

For example similiar extension [Appspector](https://chrome.google.com/webstore/detail/appspector/homgcnaoacgigpkkljjjekpignblkeae) ([repository](https://github.com/nqbao/chromesniffer)) use it [like this](https://github.com/nqbao/chromesniffer/blob/master/screenshot/small-tile.png).

**Comment by ElbertF** [comment]
Switched to pageAction in f08a5dde4d968ada145f82645275a6b9d5484877, cheers!

**Comment by hermajan** [comment]
Nice, thanks! :satisfied:

**Comment by hi-tech** [comment]
Any plans on making the old badge optional for those of us that actually relied on it?

**Comment by AliasIO** [comment]
I looked at that but it doesn't seem possible without creating two versions of the extension unfortunately.
