### ISSUE TITLE
change the sitecore logo

### ISSUE THREAD

**Issue by softineer** [ElbertF/Wappalyzer#769]
Could the sitecore logo be changed to this?

http://www.cmscritic.com/site/assets/files/4606/sitecore7.png

**Comment by softineer** [comment]
Actually, here's a link to the logo directly on the sitecore.net website.  Right-click to download and save as a png.
http://www.sitecore.net/d1yow6fhovqcc2.cloudfront.net/~/media/Redesign/Global/header-logo.ashx?ts=120914103819753

**Comment by ElbertF** [comment]
Updated in a6b91e0de26586dcde3bc1c6b53d13f5ae56f916, thanks.
