### ISSUE TITLE
Redisplays "new version installed" after forced shutdown in Firefox

### ISSUE THREAD

**Issue by ikelos** [ElbertF/Wappalyzer#774]
Hi there,

Every time firefox is forcibly shutdown and restarts, and I'm shown the "restore previous session" tab, I'm also presented with the "new version installed" tab for wappalyzer without the version number changing in the add-ons page.  This is not a major issue, but it is annoying.  Since firefox restores all my tabs automatically, I don't tend to close it first when I turn off my laptop, so whenever I come back to it, it tells me wappalyzer is a new version.  Please could you ensure that once that screen has been seen for that particular version, it is never displayed again?

Information:
Wappalyzer version 3.0.14
Mozilla Firefox 35

**Comment by gadcam** [comment]
Can't reproduce with Firefox 35.0.1 (and previous versions), Wappalyzer 3.0.14 and Windows 7.
I never experienced this.
Try to use a new profile.
Can you share with us the other addons you are using ?

**Comment by ikelos** [comment]
Hiya, I'm using the following (on Firefox 35.0 under Gentoo Linux):

Adblock Plus 2.6.7
Cert Viewer Plus 1.10
EventBug 0.1b10
Firebug 2.0.7
Live HTTP Headers 0.17
Nimbus Screen Capture 6.3.1
PrefBar 6.5.0
Web Developer 1.2.5

I'll give a new profile a test, and see if I can find more specific conditions to cause it.

**Comment by ikelos** [comment]
Sorry for the false report, it had been happening every crash for several weeks, but I now can't recreate this either, I'll refile if I get specific circumstances to recreate it.
