### ISSUE TITLE
NGINX + Pagespeed

### ISSUE THREAD

**Issue by MLWALK3R** [ElbertF/Wappalyzer#784]
Chrome extension doesn't pick up pagespeed on nginx, only on apache it does.

~# curl -I 178.32.216.44
HTTP/1.1 200 OK
Server: nginx/1.6.2
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Date: Mon, 09 Feb 2015 23:39:13 GMT
X-Page-Speed: 1.9.32.2-4321
Cache-Control: max-age=0, no-cache

**Comment by ElbertF** [comment]
Fixed, thanks @q--.

**Comment by MLWALK3R** [comment]
Nice, any idea when this will be in the next Chrome release?

**Comment by ElbertF** [comment]
Not for another few weeks, I usually wait until I have a bunch of changes lined up.

**Comment by q--** [comment]
By the way, I choose to match the entire header contents because I took the `-4321` part to be a build identifier. Is this assumption correct? Is it desirable to show this information?

**Comment by ElbertF** [comment]
The current version is `1.9.32.3`, I don't think the rest should be reported.

https://developers.google.com/speed/pagespeed/module/release_notes

**Comment by MLWALK3R** [comment]
When will this be release been a while now ;)

**Comment by AliasIO** [comment]
Fine. I just published a new version. :)

**Comment by MLWALK3R** [comment]
Thanks, Elbert ;D

**Comment by q--** [comment]
Looks like Wappalyzer.com is still using old data; it's missing e.g. SquirrelMail.

**Comment by MLWALK3R** [comment]
Its working looks like your using old data
![Alt Text](http://lel.ovh/1426950325.png)
![Al Text](http://lel.ovh/1426950566.png)

**Comment by AliasIO** [comment]
Thanks, updated.
