### ISSUE TITLE
URL bar favicons spilling out

### ISSUE THREAD

**Issue by Pezzab** [ElbertF/Wappalyzer#785]
Just noticed that the URL bar favicons are spilling out over my search box (my browser window was reduced at the time, but should imagine would also be an issue if I had extra buttons on my toolbar):

![wappalyzer-cap](https://cloud.githubusercontent.com/assets/1478964/6124825/ac07a5b6-b108-11e4-966f-dc7512e21a74.png)

Firefox or Wappalyzer?

**Comment by ElbertF** [comment]
Pretty sure that an issue with Firefox and not something we can fix.` It doesn't happen for me on Firefox Developer Edition so they may have just fixed it.

**Comment by klonos** [comment]
I'm using latest firefox 38.a1 too and don't see this issue.
