### ISSUE TITLE
Possible error in apps.json

### ISSUE THREAD

**Issue by anghelalexandra** [ElbertF/Wappalyzer#795]
Hi there,

I'm trying to use the PhantomJs driver, so far I have followed the instructions. When I run the following command:

"phantomjs driver.js http://mywebsite.com"

I get the following error:

"SyntaxError: JSON Parse error: Invalid escape character ."

If I delete the "Twitter Bootstrap" section from the apps.json file, it works fine.

**Comment by DaAwesomeP** [comment]
I must have made an error. I added an HTML regex to the Twitter Bootstrap recently.

**Comment by DaAwesomeP** [comment]
I made a pull to fix it in #797. I forgot to double escape.

**Comment by DaAwesomeP** [comment]
Fixed. This should be closed.
